### ISSUE TITLE
update ses monitor to latest alpakka

### ISSUE THREAD

**Issue by brharrington** [Netflix-Skunkworks/iep-apps#151]
The SES monitor needs to get updated to the 1.x release of alpakka which will require a bit of work because it uses the 2.x AWS SDK. Or ideally just use the AWS 2.x SDK directly to avoid the extra dependency.

This will be needed to get the project to build with scala 2.13.

**Comment by zimmermatt** [comment]
Fixed via #152.

I'll take a look at what we gain and lose by moving to use the AWS SDK directly. For now, it was relatively quick and straight-forward to update from the 1.0 milestone to the latest GA version.
